// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Yuzu_Frontend.SourceGenerators;

/// <summary>
/// 编译期扫描所有标记了 [PageAttribute] / [Page(...)] 的 UserControl 子类，
/// 生成 <c>PageRegistry.g.cs</c> 静态注册表和页面工厂字典，
/// 100% AOT 安全，不依赖运行时反射。
/// </summary>
[Generator]
public sealed class PageAttributeGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new ClassWithAttributeReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not ClassWithAttributeReceiver receiver) return;

        // 仅在 Desktop 项目中生成（非 Desktop 项目不存在 PageAttribute 类型）
        if (context.Compilation.GetTypeByMetadataName("Yuzu_Frontend.Desktop.Models.PageAttribute") == null) return;

        var pages = new List<PageDef>();
        var pageAttrShortName = "PageAttribute";
        var pageAttrFullNames = new HashSet<string>
        {
            "Yuzu_Frontend.Desktop.Models.PageAttribute",
            "PageAttribute"
        };

        foreach (var cds in receiver.Candidates)
        {
            var sm = context.Compilation.GetSemanticModel(cds.SyntaxTree);
            var rawSym = sm.GetDeclaredSymbol(cds);
            if (rawSym == null) continue;
            if (rawSym is not INamedTypeSymbol typeSymbol) continue;

            AttributeData? pageAttr = null;
            foreach (var a in typeSymbol.GetAttributes())
            {
                var attrClass = a.AttributeClass;
                if (attrClass == null) continue;
                if (attrClass.Name == pageAttrShortName
                    || attrClass.ToDisplayString() == "Yuzu_Frontend.Desktop.Models.PageAttribute")
                {
                    pageAttr = a;
                    break;
                }
            }
            if (pageAttr == null) continue;

            var def = ParsePageDef(typeSymbol, pageAttr);
            if (def != null) pages.Add(def.Value);
        }

        pages.Sort((a, b) => a.Order.CompareTo(b.Order));

        // AOT 重要：只有在当前程序集里实际检测到 [Page] 标记的类时才输出代码。
        // 原因：PageDiscoveryService + PageTypeInfo + PageAttribute 都定义在 Desktop 项目里；
        // 在共享项目（Yuzu_Frontend）中这些类型根本不存在，输出空壳代码会导致编译失败。
        // 由于共享项目中不会有任何 [Page] 标记的 View，完全跳过不会有问题。
        if (pages.Count > 0)
        {
            context.AddSource("PageRegistry.g.cs", SourceText.From(GeneratePageRegistry(pages), Encoding.UTF8));
        }
    }

    private static PageDef? ParsePageDef(INamedTypeSymbol type, AttributeData attr)
    {
        string? displayName = null;
        string? iconKind = null;
        int order = 100;
        bool isCollection = false;
        string? collectionName = null;
        string? displayCollectionName = null;

        // 构造参数 (string displayPageName, MaterialIconKind icon)
        if (attr.ConstructorArguments.Length >= 1)
        {
            displayName = attr.ConstructorArguments[0].Value?.ToString();
        }
        if (attr.ConstructorArguments.Length >= 2)
        {
            // MaterialIconKind 枚举：通常 Syntax 中是"MaterialIconKind.XXX"文本
            // 但 TypedConstant.Value 已经是枚举的底层 int 值（如果是 Enum 类型）
            var tc = attr.ConstructorArguments[2 - 1]; // i.e. index 1
            if (tc.Value != null)
            {
                if (tc.Kind == TypedConstantKind.Enum)
                {
                    // 尝试从 Syntax 节点取得原始枚举字段名（例如 "Server" from "MaterialIconKind.Server"）
                    string? enumFieldName = null;
                    try
                    {
                        if (attr.ApplicationSyntaxReference != null)
                        {
                            var attrSyntax = attr.ApplicationSyntaxReference.GetSyntax() as AttributeSyntax;
                            if (attrSyntax != null && attrSyntax.ArgumentList != null
                                && attrSyntax.ArgumentList.Arguments.Count >= 2)
                            {
                                var expr = attrSyntax.ArgumentList.Arguments[1].Expression;
                                if (expr is MemberAccessExpressionSyntax mae && mae.Name != null)
                                {
                                    enumFieldName = mae.Name.Identifier.ValueText;
                                }
                                else if (expr is IdentifierNameSyntax ins)
                                {
                                    enumFieldName = ins.Identifier.ValueText;
                                }
                            }
                        }
                    }
                    catch
                    {
                        // 忽略回溯语法节点失败，fallback 到默认值
                    }
                    iconKind = enumFieldName ?? tc.Value.ToString();
                    // 如果最终得到的是纯数字（无法解析字段名），写一个默认值避免生成无效 C# 代码
                    if (int.TryParse(iconKind, out _))
                    {
                        iconKind = "Server";
                    }
                }
                else
                {
                    iconKind = tc.Value.ToString();
                }
            }
        }

        // 命名参数：Order, IsCollection, CollectionName, DisplayCollectionName
        foreach (var np in attr.NamedArguments)
        {
            switch (np.Key)
            {
                case "Order":
                    if (np.Value.Value != null) int.TryParse(np.Value.Value.ToString(), out order);
                    break;
                case "IsCollection":
                    if (np.Value.Value != null) bool.TryParse(np.Value.Value.ToString(), out isCollection);
                    break;
                case "CollectionName":
                    collectionName = np.Value.Value?.ToString();
                    break;
                case "DisplayCollectionName":
                    displayCollectionName = np.Value.Value?.ToString();
                    break;
            }
        }

        displayName ??= type.Name;
        iconKind ??= "Server";

        var fullTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        // SymbolDisplayFormat.FullyQualifiedFormat 会加 "global::" 前缀，但我们生成代码时统一再手动加一次 global::
        if (fullTypeName.StartsWith("global::", StringComparison.Ordinal))
            fullTypeName = fullTypeName.Substring("global::".Length);

        return new PageDef(
            fullTypeName,
            displayName,
            iconKind,
            order,
            isCollection,
            collectionName,
            displayCollectionName);
    }

    private static string GeneratePageRegistry(List<PageDef> pages)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 本文件由 PageAttributeGenerator 生成，请勿手动修改。");
        sb.AppendLine("// 重新构建项目时将根据 [Page(...)] 标记自动刷新。");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Avalonia.Controls;");
        sb.AppendLine("using Material.Icons;");
        sb.AppendLine("using Yuzu_Frontend.Desktop.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace Yuzu_Frontend.Desktop.Services;");
        sb.AppendLine();
        sb.AppendLine("partial class PageDiscoveryService");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>编译期生成的页面静态注册表与工厂字典（AOT 安全）。</summary>");
        sb.AppendLine("    internal static partial class PageRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>已按 Order 升序排列的页面元信息列表。</summary>");
        sb.AppendLine("        internal static PageTypeInfo[] AllPages { get; } = new PageTypeInfo[]");
        sb.AppendLine("        {");
        foreach (var p in pages)
        {
            sb.Append("            new PageTypeInfo(");
            sb.Append("typeof(global::").Append(p.FullTypeName).Append("), ");
            sb.Append("new PageAttribute(");
            sb.Append('"').Append(Escape(p.DisplayName)).Append('"');
            sb.Append(", MaterialIconKind.").Append(p.IconKind);
            sb.Append(')');
            sb.Append(" { Order = ").Append(p.Order);
            sb.Append(", IsCollection = ").Append(p.IsCollection ? "true" : "false");
            if (!string.IsNullOrEmpty(p.CollectionName))
                sb.Append(", CollectionName = \"").Append(Escape(p.CollectionName!)).Append('"');
            if (!string.IsNullOrEmpty(p.DisplayCollectionName))
                sb.Append(", DisplayCollectionName = \"").Append(Escape(p.DisplayCollectionName!)).Append('"');
            sb.AppendLine(" }),");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>页面类型 → 强类型构造器（避免 Activator.CreateInstance 反射）。</summary>");
        sb.AppendLine("        internal static Dictionary<Type, Func<UserControl>> Factories { get; } = new Dictionary<Type, Func<UserControl>>()");
        sb.AppendLine("        {");
        foreach (var p in pages)
        {
            sb.Append("            [typeof(global::").Append(p.FullTypeName).Append(")] = () => new global::").Append(p.FullTypeName).AppendLine("(),");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Escape(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private readonly struct PageDef
    {
        public readonly string FullTypeName;
        public readonly string DisplayName;
        public readonly string IconKind;
        public readonly int Order;
        public readonly bool IsCollection;
        public readonly string? CollectionName;
        public readonly string? DisplayCollectionName;

        public PageDef(string fullTypeName, string displayName, string iconKind, int order,
            bool isCollection, string? collectionName, string? displayCollectionName)
        {
            FullTypeName = fullTypeName;
            DisplayName = displayName;
            IconKind = iconKind;
            Order = order;
            IsCollection = isCollection;
            CollectionName = collectionName;
            DisplayCollectionName = displayCollectionName;
        }
    }

    private sealed class ClassWithAttributeReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0)
            {
                Candidates.Add(cds);
            }
        }
    }
}
