// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Yuzu_Frontend.SourceGenerators;

/// <summary>
/// 编译期扫描所有带 [Category] 标记属性的 INotifyPropertyChanged 类，
/// 生成 PropertyGrid 静态分类列表，避免运行时 GetProperties / GetCustomAttribute 反射，
/// 100% AOT 安全。
///
/// <para>生成的入口：PropertyGridStaticRegistry.TryGetFactory → 返回 Func{INotifyPropertyChanged, IAvaloniaReadOnlyList{CategoryViewModel}}</para>
/// </summary>
[Generator]
public sealed class PropertyGridCategoryGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new ClassWithPropertiesReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not ClassWithPropertiesReceiver receiver) return;

        // 在当前项目中扫描带 [Category] 标记的属性类，生成静态注册表（AOT 安全）
        var targetClasses = new List<ClassDef>();
        var categoryAttrName = "CategoryAttribute";
        var displayNameAttrName = "DisplayNameAttribute";
        var filePathAttrName = "FilePathAttribute";

        foreach (var cds in receiver.Candidates)
        {
            var sm = context.Compilation.GetSemanticModel(cds.SyntaxTree);
            var rawSym = sm.GetDeclaredSymbol(cds);
            if (rawSym == null) continue;
            // GetDeclaredSymbol 返回的是 ISymbol，需要强制转换到 INamedTypeSymbol
            if (rawSym is not INamedTypeSymbol typeSym) continue;

            var props = new List<PropDef>();
            foreach (var member in typeSym.GetMembers().OfType<IPropertySymbol>())
            {
                if (!member.DeclaredAccessibility.HasFlag(Accessibility.Public)) continue;
                if (member.IsStatic) continue;

                AttributeData? categoryAttr = null;
                AttributeData? displayAttr = null;
                AttributeData? filePathAttr = null;
                foreach (var a in member.GetAttributes())
                {
                    var aname = a.AttributeClass?.Name;
                    if (aname == categoryAttrName) categoryAttr = a;
                    else if (aname == displayNameAttrName) displayAttr = a;
                    else if (aname == filePathAttrName) filePathAttr = a;
                }
                if (categoryAttr == null) continue;

                var category = categoryAttr.ConstructorArguments.Length >= 1
                    ? categoryAttr.ConstructorArguments[0].Value?.ToString() ?? "General"
                    : "General";

                var displayName = displayAttr?.ConstructorArguments.Length >= 1
                    ? displayAttr.ConstructorArguments[0].Value?.ToString() ?? member.Name
                    : member.Name;

                FilePickerModeInfo? fpMode = null;
                if (filePathAttr != null)
                {
                    // FilePathAttribute(FilePickerMode mode)
                    if (filePathAttr.ConstructorArguments.Length >= 1)
                    {
                        var raw = filePathAttr.ConstructorArguments[0].Value?.ToString();
                        // 枚举：Folder / File。字符串格式如 "FilePickerMode.File" 或整数
                        if (raw != null)
                        {
                            // 去除 "FilePickerMode." 前缀 (netstandard2.0 兼容: Replace + Ordinal 单独判断)
                            string cleaned;
                            if (raw.StartsWith("FilePickerMode.", StringComparison.Ordinal))
                                cleaned = raw.Substring("FilePickerMode.".Length);
                            else
                                cleaned = raw;
                            // netstandard 2.0 兼容：自己实现解析
                            FilePickerModeE parsed;
                            try
                            {
                                parsed = (FilePickerModeE)Enum.Parse(typeof(FilePickerModeE), cleaned, ignoreCase: true);
                                fpMode = new FilePickerModeInfo(parsed);
                            }
                            catch
                            {
                                if (int.TryParse(raw, out var i))
                                    fpMode = new FilePickerModeInfo((FilePickerModeE)i);
                            }
                        }
                    }
                    if (fpMode == null) fpMode = new FilePickerModeInfo(FilePickerModeE.File);
                }

                var typeInfo = ClassifyType(member.Type);
                props.Add(new PropDef(
                    PropertyName: member.Name,
                    Category: category,
                    DisplayName: displayName,
                    TypeInfo: typeInfo,
                    FilePathMode: fpMode));
            }

            if (props.Count == 0) continue;
            var fullName = typeSym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (fullName.StartsWith("global::", StringComparison.Ordinal))
                fullName = fullName.Substring("global::".Length);
            targetClasses.Add(new ClassDef(fullName, props));
        }

        if (targetClasses.Count > 0)
        {
            context.AddSource("PropertyGridStaticRegistry.g.cs",
                SourceText.From(GenerateRegistry(targetClasses), Encoding.UTF8));
        }
    }

    private enum FilePickerModeE { File = 0, Folder = 1 }

    private readonly record struct FilePickerModeInfo(FilePickerModeE Mode);

    private enum PropTypeE { Unknown, Bool, Int, Double, String, Enum, ComplexClass }

    private readonly record struct PropTypeInfo(PropTypeE Kind, string? EnumFullyQualifiedName = null);

    private static PropTypeInfo ClassifyType(ITypeSymbol t)
    {
        switch (t.SpecialType)
        {
            case SpecialType.System_Boolean: return new PropTypeInfo(PropTypeE.Bool);
            case SpecialType.System_Int32:
            case SpecialType.System_Int64:
            case SpecialType.System_UInt32:
            case SpecialType.System_UInt64:
            case SpecialType.System_Int16:
            case SpecialType.System_UInt16:
            case SpecialType.System_Byte:
            case SpecialType.System_SByte:
                return new PropTypeInfo(PropTypeE.Int);
            case SpecialType.System_Double:
            case SpecialType.System_Single:
            case SpecialType.System_Decimal:
                return new PropTypeInfo(PropTypeE.Double);
            case SpecialType.System_String: return new PropTypeInfo(PropTypeE.String);
        }
        if (t.TypeKind == TypeKind.Enum)
        {
            var n = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (n.StartsWith("global::", StringComparison.Ordinal)) n = n.Substring("global::".Length);
            return new PropTypeInfo(PropTypeE.Enum, n);
        }
        if (t.IsReferenceType && t.SpecialType != SpecialType.System_String)
            return new PropTypeInfo(PropTypeE.ComplexClass);
        return new PropTypeInfo(PropTypeE.Unknown);
    }

    private readonly record struct PropDef(
        string PropertyName,
        string Category,
        string DisplayName,
        PropTypeInfo TypeInfo,
        FilePickerModeInfo? FilePathMode);

    private readonly record struct ClassDef(string FullTypeName, List<PropDef> Properties);

    private static string GenerateRegistry(List<ClassDef> classes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 本文件由 PropertyGridCategoryGenerator 生成，请勿手动修改。");
        sb.AppendLine("// 重编译项目时按 [Category] / [DisplayName] / [FilePath] 标记自动刷新。");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using Avalonia.Collections;");
        sb.AppendLine("using SukiUI.Controls;");
        sb.AppendLine("using Yuzu_Frontend.Models.PropertyGrid;");
        sb.AppendLine();
        sb.AppendLine("namespace Yuzu_Frontend.Models.PropertyGrid;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>编译期生成的 PropertyGrid 静态分类注册表（AOT 安全）。</summary>");
        sb.AppendLine("internal static class PropertyGridStaticRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    private static Dictionary<Type, Func<INotifyPropertyChanged, IAvaloniaReadOnlyList<CategoryViewModel>>>? _factories;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>获取给定模型类型对应的静态分类构造器；未注册返回 false。</summary>");
        sb.AppendLine("    public static bool TryGetFactory(Type modelType, out Func<INotifyPropertyChanged, IAvaloniaReadOnlyList<CategoryViewModel>> factory)");
        sb.AppendLine("    {");
        sb.AppendLine("        EnsureFactories();");
        sb.AppendLine("        return _factories!.TryGetValue(modelType, out factory!);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void EnsureFactories()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_factories != null) return;");
        sb.AppendLine("        var dict = new Dictionary<Type, Func<INotifyPropertyChanged, IAvaloniaReadOnlyList<CategoryViewModel>>>");
        sb.AppendLine("        {");

        foreach (var cls in classes)
        {
            sb.Append("            [typeof(global::").Append(cls.FullTypeName).Append(")] = BuildCategories_")
              .Append(SafeName(cls.FullTypeName)).AppendLine(",");
        }

        sb.AppendLine("        };");
        sb.AppendLine("        _factories = dict;");
        sb.AppendLine("    }");

        // 每个类一个静态工厂方法
        foreach (var cls in classes)
        {
            sb.AppendLine();
            GenerateBuildCategoriesMethod(sb, cls);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string SafeName(string fullName)
    {
        var s = fullName;
        // 移除 global::
        if (s.StartsWith("global::", StringComparison.Ordinal)) s = s.Substring(8);
        return s.Replace(".", "_").Replace("+", "__");
    }

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static void GenerateBuildCategoriesMethod(StringBuilder sb, ClassDef cls)
    {
        var methodName = "BuildCategories_" + SafeName(cls.FullTypeName);
        var varName = "vmT";
        sb.Append("    private static IAvaloniaReadOnlyList<CategoryViewModel> ").Append(methodName)
          .Append("(INotifyPropertyChanged rawVm)").AppendLine();
        sb.AppendLine("    {");
        sb.Append("        var ").Append(varName).Append(" = (global::").Append(cls.FullTypeName).AppendLine(")rawVm;");
        sb.AppendLine("        var categories = new List<CategoryViewModel>();");
        sb.AppendLine("        // 按 Category 分组");

        // 实际代码：分组
        var groups = cls.Properties.GroupBy(p => p.Category).ToList();
        var dictVar = "groupsDict";
        sb.Append("        var ").Append(dictVar).Append(" = new Dictionary<string, AvaloniaList<IPropertyViewModel>>(StringComparer.Ordinal);").AppendLine();
        foreach (var g in groups)
        {
            sb.Append("        ").Append(dictVar).Append("[\"").Append(Escape(g.Key)).Append("\"] = new AvaloniaList<IPropertyViewModel>();").AppendLine();
        }

        // 逐个属性填充
        foreach (var p in cls.Properties)
        {
            var piExpr = $"typeof(global::{cls.FullTypeName}).GetProperty(nameof(global::{cls.FullTypeName}.{p.PropertyName}))!";
            string vmExpr;
            if (p.FilePathMode.HasValue)
            {
                vmExpr = $"new FilePathViewModel({varName}, \"{Escape(p.DisplayName)}\", {piExpr}, FilePickerMode.{(p.FilePathMode.Value.Mode == FilePickerModeE.Folder ? "Folder" : "File")})";
            }
            else
            {
                switch (p.TypeInfo.Kind)
                {
                    case PropTypeE.Bool:
                        vmExpr = $"new BoolViewModel({varName}, \"{Escape(p.DisplayName)}\", {piExpr})";
                        break;
                    case PropTypeE.Int:
                    case PropTypeE.Double:
                    case PropTypeE.String:
                        vmExpr = $"new StringViewModel({varName}, \"{Escape(p.DisplayName)}\", {piExpr})";
                        break;
                    case PropTypeE.Enum when p.TypeInfo.EnumFullyQualifiedName != null:
                        vmExpr = $"new EnumViewModel({varName}, \"{Escape(p.DisplayName)}\", {piExpr})";
                        break;
                    case PropTypeE.ComplexClass:
                        vmExpr = $"new ComplexTypeViewModel({varName}, \"{Escape(p.DisplayName)}\", {piExpr})";
                        break;
                    default:
                        vmExpr = $"new StringViewModel({varName}, \"{Escape(p.DisplayName)}\", {piExpr})";
                        break;
                }
            }
            sb.Append("        ").Append(dictVar).Append("[\"").Append(Escape(p.Category)).Append("\"]").Append(".Add(").Append(vmExpr).AppendLine(");");
        }

        // 组装 CategoryViewModel 列表，按分组顺序
        sb.AppendLine("        categories.AddRange(new[]");
        sb.AppendLine("        {");
        foreach (var g in groups)
        {
            sb.Append("            new CategoryViewModel(\"").Append(Escape(g.Key)).Append("\", ").Append(dictVar).Append("[\"").Append(Escape(g.Key)).AppendLine("\"]),");
        }
        sb.AppendLine("        });");
        sb.AppendLine("        return new AvaloniaList<CategoryViewModel>(categories);");
        sb.AppendLine("    }");
    }

    private sealed class ClassWithPropertiesReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax cds)
            {
                // 任何类都可能有带属性；在 Execute 阶段精查。
                // 只有当类成员上或自身至少有一个 Attribute 才值得过。
                bool hasAnyAttr = false;
                if (cds.AttributeLists.Count > 0) hasAnyAttr = true;
                if (!hasAnyAttr)
                {
                    foreach (var m in cds.Members)
                    {
                        if (m is PropertyDeclarationSyntax p && p.AttributeLists.Count > 0)
                        {
                            hasAnyAttr = true; break;
                        }
                    }
                }
                if (hasAnyAttr) Candidates.Add(cds);
            }
        }
    }
}
