// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Yuzu_Frontend.SourceGenerators;

/// <summary>
/// 编译期扫描所有 ViewModel（继承 ViewModelBase 或以 ViewModel 结尾的类）
/// 和所有 View（继承 Control/UserControl/Window 或以 View/Page 结尾的类），
/// 按命名约定生成静态映射字典，避免 ViewLocator 在运行时用
/// Type.GetType(string) + Activator.CreateInstance 反射。
/// 同时扫描引用程序集（如 Yuzu_Frontend 共享项目）里的 ViewModel 类型，
/// 以正确匹配 Desktop 项目中的页面 View。
/// </summary>
[Generator]
public sealed class ViewModelViewMappingGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // 无需 SyntaxReceiver，我们直接用 Compilation 扫描
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var viewModels = new List<TypeInfo>();
        var views = new List<TypeInfo>();

        var controlBaseFullNames = new HashSet<string>
        {
            "Avalonia.Controls.Control",
            "Avalonia.Controls.UserControl",
            "Avalonia.Controls.Window",
            "Avalonia.Controls.ContentControl",
            "SukiUI.Controls.SukiWindow",
        };
        var viewModelBaseFullNames = new HashSet<string>
        {
            "Yuzu_Frontend.ViewModels.ViewModelBase",
            "Yuzu_Frontend.ViewModels.ToastsViewModel",
        };

        // 收集所有 INamedTypeSymbol：当前编译 + 所有引用程序集
        var allTypes = new List<INamedTypeSymbol>();
        AddNamespaceTypes(context.Compilation.GlobalNamespace, allTypes);

        foreach (var sym in allTypes)
        {
            // 只扫描以 "Yuzu_Frontend" 前缀的命名空间类型，避免第三方库（Avalonia/SukiUI）中的噪音
            var ns = sym.ContainingNamespace?.ToDisplayString() ?? "";
            if (!ns.StartsWith("Yuzu_Frontend", StringComparison.Ordinal))
                continue;

            // 过滤：必须是非内部类型、非泛型、可构造（有公共无参构造函数或作为 ViewModel 允许没有）
            if (sym.DeclaredAccessibility != Accessibility.Public && sym.DeclaredAccessibility != Accessibility.Internal)
                continue;

            var isView = InheritsFrom(sym, controlBaseFullNames);
            var isViewModel = !sym.IsGenericType
                              && (InheritsFrom(sym, viewModelBaseFullNames)
                                  || sym.Name.EndsWith("ViewModel", StringComparison.Ordinal));

            if (isView)
            {
                // View 必须有公共无参构造函数才能 new()
                var hasCtor = sym.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);
                if (!hasCtor) continue;
                var full = sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (full.StartsWith("global::", StringComparison.Ordinal)) full = full.Substring("global::".Length);
                views.Add(new TypeInfo(full, sym.Name, sym.ContainingNamespace?.ToDisplayString() ?? ""));
            }
            if (isViewModel)
            {
                var full = sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (full.StartsWith("global::", StringComparison.Ordinal)) full = full.Substring("global::".Length);
                viewModels.Add(new TypeInfo(full, sym.Name, sym.ContainingNamespace?.ToDisplayString() ?? ""));
            }
        }

        var mappings = new List<Mapping>();
        foreach (var vm in viewModels)
        {
            var candidates = ComputeViewNameCandidates(vm.Name);
            TypeInfo? matched = null;
            // (1) 同命名空间
            foreach (var cand in candidates)
            {
                var t = views.FirstOrDefault(v => v.Name == cand && v.Namespace == vm.Namespace);
                if (!string.IsNullOrEmpty(t.FullName)) { matched = t; break; }
            }
            // (2) 跨命名空间查找（Views 子命名空间 / Desktop.Views 等）
            if (matched == null)
            {
                foreach (var cand in candidates)
                {
                    var t = views.FirstOrDefault(v => v.Name == cand);
                    if (!string.IsNullOrEmpty(t.FullName)) { matched = t; break; }
                }
            }
            if (matched.HasValue && !string.IsNullOrEmpty(matched.Value.FullName))
                mappings.Add(new Mapping(vm, matched.Value));
        }

        context.AddSource("ViewLocatorStaticRegistry.g.cs",
            SourceText.From(GenerateRegistry(mappings), Encoding.UTF8));
    }

    private static void AddNamespaceTypes(INamespaceSymbol ns, List<INamedTypeSymbol> result)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol childNs)
                AddNamespaceTypes(childNs, result);
            else if (member is INamedTypeSymbol namedType)
            {
                result.Add(namedType);
                if (namedType.TypeKind == TypeKind.Class || namedType.TypeKind == TypeKind.Struct)
                {
                    foreach (var nested in namedType.GetTypeMembers())
                        AddNestedTypes(nested, result);
                }
            }
        }
    }

    private static void AddNestedTypes(INamedTypeSymbol type, List<INamedTypeSymbol> result)
    {
        result.Add(type);
        foreach (var nested in type.GetTypeMembers())
            AddNestedTypes(nested, result);
    }

    private static List<string> ComputeViewNameCandidates(string vmName)
    {
        var list = new List<string>();
        if (vmName.EndsWith("ViewModel", StringComparison.Ordinal))
        {
            var prefix = vmName.Substring(0, vmName.Length - "ViewModel".Length);
            list.Add(prefix + "View");
            list.Add(prefix + "Page");
            list.Add(prefix);
        }
        if (vmName.EndsWith("PageViewModel", StringComparison.Ordinal))
        {
            var prefix = vmName.Substring(0, vmName.Length - "PageViewModel".Length);
            list.Insert(0, prefix + "Page");
            list.Insert(1, prefix + "PageView");
        }
        return list;
    }

    private static bool InheritsFrom(INamedTypeSymbol sym, HashSet<string> baseFullNames)
    {
        var t = sym.BaseType;
        while (t != null)
        {
            var full = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (baseFullNames.Contains(full)) return true;
            var simple = t.ContainingNamespace != null
                ? t.ContainingNamespace.ToDisplayString() + "." + t.Name
                : t.Name;
            if (baseFullNames.Contains(simple)) return true;
            t = t.BaseType;
        }
        return false;
    }

    private readonly record struct TypeInfo(string FullName, string Name, string Namespace);
    private readonly record struct Mapping(TypeInfo ViewModel, TypeInfo View);

    private static string GenerateRegistry(List<Mapping> mappings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 本文件由 ViewModelViewMappingGenerator 生成，请勿手动修改。");
        sb.AppendLine("// 编译期根据命名约定（XxxViewModel ↔ XxxView/XxxPage）自动生成映射表。");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Avalonia.Controls;");
        sb.AppendLine();
        sb.AppendLine("namespace Yuzu_Frontend;");
        sb.AppendLine();
        sb.AppendLine("partial class ViewLocator");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>编译期生成的 ViewModel → View 静态工厂映射（AOT 安全）。</summary>");
        sb.AppendLine("    internal static IReadOnlyDictionary<Type, Func<Control>> StaticMappings { get; } = new Dictionary<Type, Func<Control>>()");
        sb.AppendLine("    {");
        foreach (var m in mappings)
        {
            sb.Append("        [typeof(global::").Append(m.ViewModel.FullName).Append(")] = () => new global::")
              .Append(m.View.FullName).AppendLine("(),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>快速查询：给定 ViewModel 类型查找视图工厂；找不到返回 null。</summary>");
        sb.AppendLine("    internal static Func<Control>? GetFactoryForViewModelType(Type viewModelType)");
        sb.AppendLine("        => StaticMappings.TryGetValue(viewModelType, out var factory) ? factory : null;");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
