// netstandard2.0 polyfill：C# 9 的 record / init-only 属性依赖此类型。
// 当项目目标框架为 netstandard2.0 时 Roslyn 编译器找不到该类型，
// 于是我们在本项目内自己声明同名同命名空间的类型即可（编译器只检查"存在性"）。
// <auto-generated/>
#pragma warning disable IDE0130 // 命名空间与文件夹结构不一致
namespace System.Runtime.CompilerServices
{
    using System.ComponentModel;
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal static class IsExternalInit { }
}
#pragma warning restore IDE0130
